name: Build

on:
  push:
    branches: [ 3.0.x ]
  pull_request:
    branches: [ 3.0.x ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ["11", "16"]

    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: ./scripts/runAcceptanceTests.sh
